apiVersion: apps/v1
kind: Deployment
metadata:
  name: pywhoami
spec:
  selector:
    matchLabels:
      app: pywhoami
  template:
    metadata:
      labels:
        app: pywhoami
    spec:
      containers:
      - name: pywhoami
        image: rpeets/pywhoami:1.2.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: pywhoami-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: pywhoami-secret
                key: password
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /
            port: http
